version: '3.5'
name: php-site


services:


  php:
    image: php
    container_name: php
    volumes:
      - './site:/var/www/html'
      - './php.conf:/usr/local/etc/php-fpm.d/zz-log.conf'
    depends_on:
      - mariadb

  nginx:
    container_name: web
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - './site:/var/www/html'
      - './nginx:/etc/nginx/conf.d'
    depends_on:
      - php

  mariadb:
    container_name: db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: YOURPASSWORDHERE
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
    name: mysqldata
networks:
  siteNet:
    ipam:
      config:
        - subnet: 192.168.75.0/24


















